clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  eslint:
    group: install
    image: marcbachmann/eslint:4.19.1

  test:
    group: test
    image: node:10-alpine
    commands: ["npm install"]

  release:
    group: publish
    image: marcbachmann/semantic-release:15.1.3
    secrets: [gh_token]
    when:
      event: push
